// Generated by CoffeeScript 1.8.0
(function() {
  console.log('bg.html starting!');

  chrome.tabs.onUpdated.addListener(function(tabId) {
    return chrome.pageAction.show(tabId);
  });

  chrome.tabs.getSelected(null, function(tab) {
    return chrome.pageAction.show(tab.id);
  });

  chrome.pageAction.onClicked.addListener(function(tab) {
    return chrome.tabs.getSelected(null, function(tab) {
      return chrome.tabs.sendRequest(tab.id, {
        callFunction: "toggleSB"
      }, function(response) {
        return console.log(response);
      });
    });
  });

  console.log('bg.html done.');

}).call(this);
